return {
  "folke/which-key.nvim",
  "christoomey/vim-tmux-navigator",
  "tpope/vim-surround",
  "tpope/vim-unimpaired",
  "ggandor/leap.nvim",
  "tpope/vim-repeat",
  "vim-airline/vim-airline",
  "vim-airline/vim-airline-themes",
  "godlygeek/tabular",
  {
    "nvim-tree/nvim-tree.lua",
    version = "*",
    dependencies = {
      "nvim-tree/nvim-web-devicons",
    },
    config = function()
      require("nvim-tree").setup {}
    end,
  },
  "akinsho/bufferline.nvim",
  "editorconfig/editorconfig-vim",
  "plasticboy/vim-markdown",
  "windwp/nvim-autopairs",
  "nvim-lua/plenary.nvim",
  {
    'nvim-telescope/telescope.nvim',
    tag = '0.1.1',
    dependencies = { 'nvim-lua/plenary.nvim' }
  },
  { 'nvim-telescope/telescope-fzf-native.nvim',
                                                  build =
    'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' },
  { "nvim-treesitter/nvim-treesitter",          build = ":TSUpdate" },
  "mhinz/vim-startify",
  "dstein64/vim-startuptime",
  "scrooloose/vim-slumlord",
  "aklt/plantuml-syntax",
  "junegunn/limelight.vim",
  "junegunn/goyo.vim",
  "terrastruct/d2-vim",
  { "iamcco/markdown-preview.nvim", build = "cd app && yarn install" },
  "lewis6991/gitsigns.nvim",
  "tpope/vim-fugitive",
  "preservim/nerdcommenter",
  "neovim/nvim-lspconfig",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "hrsh7th/nvim-cmp",
  "AndrewRadev/splitjoin.vim",
  "Yggdroot/indentLine",
  "mileszs/ack.vim",
  "dag/vim-fish",
  "L3MON4D3/LuaSnip",
  "saadparwaiz1/cmp_luasnip",
  "rafamadriz/friendly-snippets",
  "simrat39/symbols-outline.nvim",
  "ThePrimeagen/refactoring.nvim",
  "folke/trouble.nvim",
  "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
  "sindrets/diffview.nvim",
  "antoinemadec/FixCursorHold.nvim",
  "nvim-neotest/neotest",
  "sebdah/vim-delve",
  "pangloss/vim-javascript",
  "peitalin/vim-jsx-typescript",
  "jparise/vim-graphql",
  "leafgarland/typescript-vim",
  "MaxMEllon/vim-jsx-pretty",
  "dracula/vim",
  "AlessandroYorba/Alduin",
  "chriskempson/base16-vim",
  "arcticicestudio/nord-vim",
  {
    "rebelot/kanagawa.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      -- load the colorscheme here
      vim.cmd([[colorscheme kanagawa]])
    end,
  },
  "pearofducks/ansible-vim",
  "hashivim/vim-terraform",
  "vim-scripts/avrasm.vim",
  "mfussenegger/nvim-jdtls",
  {
    "rcarriga/nvim-dap-ui",
    dependencies = {
      "mfussenegger/nvim-dap"
    },
    config = true,
  },
}
